/* SCRIPT CREADO POR LA BACHILLER MARIA TERESA MELENDEZ SERRANO, ESTUDIANTE DE INGENIERIA DE SISTEMAS
EN LA UNIVERSIDAD DE EL SALVADOR, EL PRESENTE SCRIPT MUESTRA UNA FIGURA GEOMETRICA FORMADA POR UN CUADRO Y CUATRO TRIANGULOS*/
//DECLARACION DE LIBRERIAS A USAR
#include <windows.h>// PERMITE EL USO DE ESTE GLUT EN WINDOWS
#include <GL/gl.h>// PERMITE USO DE OPEN GL
#include <GL/glut.h>// PERMITE EL USODE GLUT
void fig(void) // CREACION DE FUNCION DISPLAY DONDE DIBUJAREMOS LA FIGURA
	{
	    glClear (GL_COLOR_BUFFER_BIT);// LIMPIANDOCOLOR DE PANTALLA
	glColor3f (0, 0, 0.5);// COLOCANDO COLOOR AL CUADRADO EN AZUL OSCURO
	glBegin(GL_QUADS);// DIBUANJANDO UN CUADRADO
	glVertex2d (-0.25, 0.25);
	glVertex2d (0.25,0.25);
    glVertex2d (0.25,-0.25);
	glVertex2d (-0.25,-0.25);

	glEnd();

	glColor3f (1,0.7, 0);// DANDO COLOR AL TRIANGULO DE ARRIBA DE AMARILLO
	glBegin(GL_TRIANGLES);//ESPECIFICANDO QUE SE DIBUJARA UN TRIANGULO
	glVertex2d (0, 0.6);
	glVertex2d (-0.25,0.25);
    glVertex2d (0.25,0.25);

	glEnd();

		glColor3f (0, 1.0, 0);// DANCO COLOR AL TRIANGULO DERECHO EN VERDE
	glBegin(GL_TRIANGLES);// ESPECIFICANDO QUE SE DIBUJARA UN TRIANGULO
	glVertex2d (0.6, 0);
	glVertex2d (0.25,0.25);
    glVertex2d (0.25,-0.25);

	glEnd();
		glColor3f (0.75, 0, 0); //DANDO COLOR AL TRIANGULO DE ABAJO EN ROJO
	glBegin(GL_TRIANGLES);// ESPECIFICANDO QUE SE DIBUJARA UN TRIANGULO
	glVertex2d (0,-0.6);
	glVertex2d (-0.25,-0.25);
    glVertex2d (0.25,-0.25);

	glEnd();
		glColor3f (0, 1.0, 0);//DANDO COLOR AL TRIANGULO IZQUIERDO EN COLOR VERDE
	glBegin(GL_TRIANGLES);// ESPECIFICANDO QUE SE DIBUJA UN TRIANGULO
	glVertex2d (-0.6, 0);
	glVertex2d (-0.25,0.25);
    glVertex2d (-0.25,-0.25);

	glEnd();
	glFlush();
}


int main(int argc, char** argv)// INICIALIZANDO FUNCION PRINCIPAL MAIN
{
	glutInit (&argc, argv);// INICIALIZANDO COMPONENTES DEL GLUT
	glutInitDisplayMode (GLUT_SINGLE | GLUT_RGB);//DEFINIENDO COLORES
    glutInitWindowSize(550,400); //DEFINIENDO TAMANO DE VENTANA
	glutInitWindowPosition(250,250); // DEFINIENDO POSICION DE LA VENTANA
	glutCreateWindow("figura 1"); // CREANDO LA VENTANA
	glutDisplayFunc(fig); //LLAMANDO A LA FUNCION FIG PARA DIBUJAR
	glutMainLoop(); //ENLAZANDO FUNCION Y PROGRAMA PRINCIPAL
	return 0;//RETORNANDO AL SISTEMA
}

