
/* PROGRAMA REALIZADO POR LA BACHILLER MARIA TERESA MELENDEZ SERRANO, ESTUDIANTE DE INGENIERIA DE SISTEMAS EN LA UNIVERSIDAD DE EL SALVADOR,
EL PRESENTE SCRIPT MUESTRA LA FORMACION DE UNA CIRCUNSFERENCIA POR MEDIO DEL DIBUJO DE 50 PUNTOS GRAFICOS. */
//INCLUSION DE LIBRERIAS A USAR
#include <windows.h>// SERVIRA PARA UTILIZAR EL GLUT EN WINDOWS
#include <GL/gl.h>// SERVIRA PARA USAR OPEN GL
#include <GL/glut.h>// SERVIRA PARA USAR GLUT
#include <math.h>// SERVIRA PARA REALIZAR OPERACIONES MATEMATICAS

void display()// CREANDO FUNCION DISPLAY DONDE DIBUJAREMOS EL CIRCULO DE PUNTOS
{
	glClear(GL_COLOR_BUFFER_BIT);//LIMPIANDO COLOR DE PANTALLA
	glColor3f(1,1,1); //DECLARANDO EL COLOR QUE QUEREMOS QUE SEAN LOS PUNTOS, EN ESTE CASO ES BLANCO
	glPointSize(4); //TAMANO EN EL CUAL QUERREMOS LOS PUNTOS
	glBegin(GL_POINTS);//DIBUJANDO LOS PUNTOS
 float  angulo;// DECLARANDO UNA VARIABLE
	 for (float i=0; i<360; i+=7.2)//USAREMOS FOR PUESTO QUE DIBUJAREMOS MUCHOS PUNTOS  , COLOCAMOS COMO INCREMENTO 7.2 PORQUE 360/50 PUNTOS ES 7.2
{
    angulo = (GLfloat)i*3.16/180; //CONVERTIMOS LOS GRADOS A RADIANES
      glVertex2d(0.5*cos(angulo), 0.5*sin(angulo)); //CREAMOS EL PUNTO DEPENDIENDO EL ANGULO QUE NOS INDIQUE I ,CON UN RADIO DE 0.5


}

	glEnd();

	glFlush(); //REFORZAMOS EL PINTADO
}

int main(int argc, char** argv) //CREACION DE FUNCION PRINCIPAL MAIN
{
	glutInit (&argc, argv);// INICIALIZAMOS GLUT
	glutInitDisplayMode (GLUT_SINGLE | GLUT_RGB);// NOS PERMITIRA LA SERIE DE COLORES A USAR
    glutInitWindowSize(500,500); // TAMANO DE LA VENTANA
	glutInitWindowPosition(50,50); // POSICION DE LA VENTANA
		glutCreateWindow("circulo"); // CREACION DE LA VENTANA CON EL NOMBRE CIRCULO
	glutDisplayFunc(display); //LLAMAMOS A LA FUNCION DISPLAY
	glutMainLoop(); //ENLACE ENTRE FUNCION Y PROGRAMA PRINCIPAL
	return 0;//RETORNO A SISTEMA
}


